import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./Components/sidebar";
import Usernav from "./Components/navprofile";
import user from "./mockdb/user.json";
import Footer from "./Components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="grid grid-cols-5 grid-rows-3 h-screen">
           <div className="col-span-1 row-span-2">
             <Sidebar />
           </div>
           <div className="col-span-4 row-span-1">
             <Usernav user={user}/>
             {children}
           </div>
            <div className="col-span-5 row-span-1 content-end">
              <Footer />
            </div>
        </div>
       
      </body>
    </html>
  );
}
